version: '3.9'

services:
  database:
    image: mysql
    restart: always 
    environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_USER: web 
        MYSQL_PASSWORD: gintoki
        MYSQL_DATABASE: snippetbox
    ports:
      - "3308:3308"
    
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  adminer:
    image: adminer 
    restart: always 
    environment:
      ADMINER_DESIGN: brade
    ports:
      - "3333:8080"
