**/*.go {
    prep: go test @dirmods
}

#Reload the application if any template file changes
**/*.go !**/*_test.go **/ui/html/**/*.tmpl{
    prep:go build -o Snippetbox-Go ./cmd/web/
    daemon +sigterm: ./Snippetbox-Go
}

